name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        npm install
        npm run build
        docker login --username shihaowang123 --password ${{ secrets.ALI_PASSWORD }} registry.cn-shanghai.aliyuncs.com
        docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/sdev/carrot-sprit-backend:latest
        docker push registry.cn-shanghai.aliyuncs.com/sdev/carrot-sprit-backend:latest
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 47.102.122.82
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        script: docker pull registry.cn-shanghai.aliyuncs.com/sdev/carrot-sprit-backend:latest && docker rm -f sprits && docker run --name sprits -d -p 5300:3000 registry.cn-shanghai.aliyuncs.com/sdev/carrot-sprit-backend:latest
